application/activemessage
application/andrew-inset
application/applefile
application/atomicmail
application/batch-SMTP
application/beep+xml
application/cals-1840
application/commonground
application/cybercash
application/dca-rft
application/dec-dx
application/dvcs
application/EDI-Consent
application/EDIFACT
application/EDI-X12
application/eshop
application/font-tdpfr
application/http
application/hyperstudio
application/iges
application/index
application/index.cmd
application/index.obj
application/index.response
application/index.vnd
application/iotp
application/ipp
application/isup
application/java-archive
application/mac-binhex40
application/mac-compactpro
application/macwriteii
application/marc
application/mathematica
application/mathematica-old
application/msexcel
application/msword
application/news-message-id
application/news-transmission
application/ocsp-request
application/ocsp-response
application/octet-stream
application/oda
application/parityfec
application/pdf
application/pgp-encrypted
application/pgp-keys
application/pgp-signature
application/pkcs10
application/pkcs7-mime
application/pkcs7-signature
application/pkix-cert
application/pkixcmp
application/pkix-crl
application/postscript
application/powerpoint
application/prs.alvestrand.titrax-sheet
application/prs.cww
application/prs.nprend
application/qif
application/qsig
application/remote-printing
application/riscos
application/rtf
application/sdp
application/set-payment
application/set-payment-initiation
application/set-registration
application/set-registration-initiation
application/sgml
application/sgml-open-catalog
application/sieve
application/slate
application/smil
application/timestamp-query
application/timestamp-reply
application/vemmi
application/vnd.3M.Post-it-Notes
application/vnd.accpac.simply.aso
application/vnd.accpac.simply.imp
application/vnd.acucobol
application/vnd.aether.imp
application/vnd.anser-web-certificate-issue-initiation
application/vnd.anser-web-funds-transfer-initiation
application/vnd.audiograph
application/vnd.bmi
application/vnd.businessobjects
application/vnd.canon-cpdl
application/vnd.canon-lips
application/vnd.claymore
application/vnd.commerce-battelle
application/vnd.commonspace
application/vnd.comsocaller
application/vnd.contact.cmsg
application/vnd.cosmocaller
application/vnd.ctc-posml
application/vnd.cups-postscript
application/vnd.cups-raster
application/vnd.cups-raw
application/vnd.cybank
application/vnd.dna
application/vnd.dpgraph
application/vnd.dxr
application/vnd.ecdis-update
application/vnd.ecowin.chart
application/vnd.ecowin.filerequest
application/vnd.ecowin.fileupdate
application/vnd.ecowin.series
application/vnd.ecowin.seriesrequest
application/vnd.ecowin.seriesupdate
application/vnd.enliven
application/vnd.epson.esf
application/vnd.epson.msf
application/vnd.epson.quickanime
application/vnd.epson.salt
application/vnd.epson.ssf
application/vnd.ericsson.quickcall
application/vnd.eudora.data
application/vnd.fdf
application/vnd.ffsns
application/vnd.FloGraphIt
application/vnd.framemaker
application/vnd.fsc.weblaunch
application/vnd.fujitsu.oasys
application/vnd.fujitsu.oasys2
application/vnd.fujitsu.oasys3
application/vnd.fujitsu.oasysgp
application/vnd.fujitsu.oasysprs
application/vnd.fujixerox.ddd
application/vnd.fujixerox.docuworks
application/vnd.fujixerox.docuworks.binder
application/vnd.fut-misnet
application/vnd.grafeq
application/vnd.groove-account
application/vnd.groove-identity-message
application/vnd.groove-injector
application/vnd.groove-tool-message
application/vnd.groove-tool-template
application/vnd.groove-vcard
application/vnd.hhe.lesson-player
application/vnd.hp-HPGL
application/vnd.hp-hpid
application/vnd.hp-hps
application/vnd.hp-PCL
application/vnd.hp-PCLXL
application/vnd.httphone
application/vnd.hzn-3d-crossword
application/vnd.ibm.afplinedata
application/vnd.ibm.MiniPay
application/vnd.ibm.modcap
application/vnd.informix-visionary
application/vnd.intercon.formnet
application/vnd.intertrust.digibox
application/vnd.intertrust.nncp
application/vnd.intu.qbo
application/vnd.intu.qfx
application/vnd.irepository.package+xml
application/vnd.is-xpr
application/vnd.japannet-directory-service
application/vnd.japannet-jpnstore-wakeup
application/vnd.japannet-payment-wakeup
application/vnd.japannet-registration
application/vnd.japannet-registration-wakeup
application/vnd.japannet-setstore-wakeup
application/vnd.japannet-verification
application/vnd.japannet-verification-wakeup
application/vnd.koan
application/vnd.lotus-1-2-3
application/vnd.lotus-approach
application/vnd.lotus-freelance
application/vnd.lotus-notes
application/vnd.lotus-organizer
application/vnd.lotus-screencam
application/vnd.lotus-wordpro
application/vnd.mcd
application/vnd.mediastation.cdkey
application/vnd.meridian-slingshot
application/vnd.mif
application/vnd.minisoft-hp3000-save
application/vnd.mitsubishi.misty-guard.trustweb
application/vnd.mobius.daf
application/vnd.mobius.dis
application/vnd.mobius.msl
application/vnd.mobius.plc
application/vnd.mobius.txf
application/vnd.motorola.flexsuite
application/vnd.motorola.flexsuite.adsi
application/vnd.motorola.flexsuite.fis
application/vnd.motorola.flexsuite.gotap
application/vnd.motorola.flexsuite.kmr
application/vnd.motorola.flexsuite.ttc
application/vnd.motorola.flexsuite.wem
application/vnd.mozilla.xul+xml
application/vnd.ms-artgalry
application/vnd.ms-asf
application/vnd.mseq
application/vnd.ms-excel
application/vnd.msign
application/vnd.ms-lrm
application/vnd.ms-powerpoint
application/vnd.ms-project
application/vnd.ms-tnef
application/vnd.ms-works
application/vnd.musician
application/vnd.music-niff
application/vnd.netfpx
application/vnd.noblenet-directory
application/vnd.noblenet-sealer
application/vnd.noblenet-web
application/vnd.novadigm.EDM
application/vnd.novadigm.EDX
application/vnd.novadigm.EXT
application/vnd.osa.netdeploy
application/vnd.palm
application/vnd.pg.format
application/vnd.pg.osasli
application/vnd.powerbuilder6
application/vnd.powerbuilder6-s
application/vnd.powerbuilder7
application/vnd.powerbuilder75
application/vnd.powerbuilder75-s
application/vnd.powerbuilder7-s
application/vnd.previewsystems.box
application/vnd.publishare-delta-tree
application/vnd.pvi.ptid1
application/vnd.pwg-xhtml-print+xml
application/vnd.rapid
application/vnd.s3sms
application/vnd.seemail
application/vnd.shana.informed.formdata
application/vnd.shana.informed.formtemplate
application/vnd.shana.informed.interchange
application/vnd.shana.informed.package
application/vnd.sss-cod
application/vnd.sss-dtf
application/vnd.sss-ntf
application/vnd.stardivision.calc
application/vnd.stardivision.impress
application/vnd.stardivision.writer
application/vnd.street-stream
application/vnd.svd
application/vnd.swiftview-ics
application/vnd.triscape.mxs
application/vnd.trueapp
application/vnd.truedoc
application/vnd.tve-trigger
application/vnd.ufdl
application/vnd.uplanet.alert
application/vnd.uplanet.alert-wbxml
application/vnd.uplanet.bearer-choice
application/vnd.uplanet.bearer-choice-wbxml
application/vnd.uplanet.cacheop
application/vnd.uplanet.cacheop-wbxml
application/vnd.uplanet.channel
application/vnd.uplanet.channel-wbxml
application/vnd.uplanet.list
application/vnd.uplanet.listcmd
application/vnd.uplanet.listcmd-wbxml
application/vnd.uplanet.list-wbxml
application/vnd.uplanet.signal
application/vnd.vcx
application/vnd.vectorworks
application/vnd.vidsoft.vidconference
application/vnd.visio
application/vnd.vividence.scriptfile
application/vnd.wap.sic
application/vnd.wap.slc
application/vnd.wap.wbxml
application/vnd.wap.wmlc
application/vnd.wap.wmlscriptc
application/vnd.webturbo
application/vnd.wrq-hp3000-labelled
application/vnd.wt.stf
application/vnd.xara
application/vnd.xfdl
application/vnd.yellowriver-custom-menu
application/whoispp-query
application/whoispp-response
application/wita
application/wordperfect5.1
application/wordperfect
application/x400-bp
application/x-abiword
application/x-applixgraphics 
application/x-applixspread
application/x-applix-spreadsheet
application/x-applixword
application/x-applix-word
application/x-archive
application/x-artsbuilder
application/x-asp
application/x-awk
application/x-backup
application/x-bcpio
application/x-bzip2
application/x-bzip-compressed-tar
application/x-cdlink
application/x-cgi
application/x-chess-pgn
application/x-class-file
application/x-compress
application/x-compressed-tar
application/x-core
application/x-core-file
application/x-cpio-compressed
application/x-cpio
application/x-csh
application/x-deb
application/x-debian-package
application/x-designer
application/x-desktop
application/x-dia-diagram
application/x-director
application/x-dvi
application/x-e-theme
application/x-font-afm
application/x-font-linux-psf
application/x-font
application/x-futuresplash
application/x-glade
application/x-gnucash
application/x-gtar
application/x-gzip
application/x-hdf
application/xhtml+xml
application/x-jar
application/x-java
application/x-java-byte-code
application/x-javascript
application/x-jbuilder-project
application/x-kchart
application/x-kde-app-info
application/x-kformula
application/x-killustrator
application/x-kivio
application/x-koan
application/x-konsole
application/x-kpresenter
application/x-krayon
application/x-kspread
application/x-ksysguard
application/x-ksysv-package
application/x-ktheme
application/x-kugar
application/x-kword
application/x-latex
application/x-lhz
application/x-linguist
application/x-lzop
application/x-mif
application/xml
application/xml-dtd
application/xml-external-parsed-entity
application/x-netcdf
application/x-object
application/x-object-file
application/x-oleo
application/x-perl
application/x-php
application/x-profile
application/x-python-bytecode
application/x-python
application/x-quattropro
application/x-qw
application/x-rar-compressed
application/x-reject
application/x-rpm
application/x-sharedlib
application/x-shared-library-la
application/x-shared-library
application/x-shar
application/x-shellscript
application/x-shockwave-flash
application/x-sh
application/x-smil
application/x-staroffice-presentation
application/x-staroffice-spreadsheet
application/x-staroffice-words
application/x-stuffit
application/x-sv4cpio
application/x-sv4crc
application/x-tar
application/x-tarz
application/x-tbz
application/x-tcl
application/x-tex-gf
application/x-texinfo
application/x-tex-pk
application/x-tex
application/x-tgz
application/x-theme
application/x-trash
application/x-troff-man-compressed
application/x-troff-man
application/x-troff-me
application/x-troff-ms
application/x-troff
application/x-truetype-font
application/x-tzo
application/x-unix-archive
application/x-ustar
application/x-wais-source
application/x-xbase
application/x-zip
application/x-zip-compressed
application/zip
audio/32kadpcm
audio/ac3
audio/basic
audio/g.722.1
audio/l16
audio/midi
audio/mp4a-latm
audio/mpa-robust
audio/mpeg
audio/parityfec
audio/prs.sid
audio/telephone-event
audio/tone
audio/vnd
audio/vnd.cisco.nse
audio/vnd.cns.anp1
audio/vnd.cns.inf1
audio/vnd.digital-winds
audio/vnd.everad.plj
audio/vnd.lucent.voice
audio/vnd.nortel.vbk
audio/vnd.nuera.ecelp4800
audio/vnd.nuera.ecelp7470
audio/vnd.nuera.ecelp9600
audio/vnd.octel.sbc
audio/vnd.qcelp
audio/vnd.rhetorex.32kadpcm
audio/vnd.vmx.cvsd
audio/x-adpcm
audio/x-aiff
audio/x-it
audio/x-karaoke
audio/x-mpeg
audio/x-mpegurl
audio/x-ogg
audio/x-pn-realaudio-plugin
audio/x-pn-realaudio
audio/x-realaudio
audio/x-s3m
audio/x-scpls
audio/x-stm
audio/x-ulaw
audio/x-voc
audio/x-wav
audio/x-xi
audio/x-xm
chemical/x-pdb
chemical/x-xyz
image/bmp
image/cgm
image/fax-g3
image/g3fax
image/gif
image/ief
image/ico
image/jpeg
image/pjpeg
image/naplps
image/png
image/x-png
image/prs.btif
image/prs.pti
image/svg+xml
image/tiff
image/vnd.cns.inf2
image/vnd.djvu
image/vnd
image/vnd.dwg
image/vnd.dxf
image/vnd.fastbidsheet
image/vnd.fpx
image/vnd.fst
image/vnd.fujixerox.edmics-mmr
image/vnd.fujixerox.edmics-rlc
image/vnd.mix
image/vnd.net-fpx
image/vnd.svf
image/vnd.wap.wbmp
image/vnd.xiff
image/x-3ds
image/x-applix-graphic
image/x-cmu-raster
image/x-compressed-xcf
image/x-eps
image/x-iff
image/x-ilbm
image/x-jng
image/x-lwo
image/x-lws
image/x-msod
image/x-photo-cd
image/x-portable-anymap
image/x-portable-bitmap
image/x-portable-graymap
image/x-portable-pixmap
image/x-psd
image/x-rgb
image/x-tga
image/x-xbitmap
image/x-xbm
image/x-xcf-gimp
image/x-xcf
image/x-xpixmap
image/x-xpm
image/x-xwindowdump
image/x-MS-bmp
inode/blockdevice
inode/chardevice
inode/directory
inode/directory-locked
inode/fifo
inode/socket
message/delivery-status
message/disposition-notification
message/external-body
message/http
message/news
message/partial
message/rfc822
message/s-http
message/x-gnu-rmail
model/iges
model/mesh
model/vnd.dwf
model/vnd.flatland.3dml
model/vnd.gdl
model/vnd.gs-gdl
model/vnd.gtw
model/vnd.mts
model/vnd.vtu
model/vrml
multipart/alternative
multipart/appledouble
multipart/byteranges
multipart/digest
multipart/encrypted
multipart/form-data
multipart/header-set
multipart/mixed
multipart/parallel
multipart/related
multipart/report
multipart/signed
multipart/voice-message
text/abiword
text/bib
text/calendar
text/css
text/directory
text/english
text/enriched
text/html
text/mathml
text/parityfec
text/plain
text/prs.lines.tag
text/rdf
text/rfc822-headers
text/richtext
text/rss
text/rtf
text/sgml
text/spreadsheet
text/t140
text/tab-separated-values
text/uri-list
text/vnd.abc
text/vnd.curl
text/vnd.DMClientScript
text/vnd.flatland.3dml
text/vnd.fly
text/vnd.fmi.flexstor
text/vnd.in3d.3dml
text/vnd.in3d.spot
text/vnd.IPTC.NewsML
text/vnd.IPTC.NITF
text/vnd.latex-z
text/vnd.motorola.reflex
text/vnd.ms-mediapackage
text/vnd.sun.j2me.app-descriptor
text/vnd.wap.si
text/vnd.wap.sl
text/vnd.wap.wmlscript
text/vnd.wap.wml
text/x-authors
text/x-chdr
text/x-copying
text/x-credits
text/x-csh
text/x-csrc
text/x-dcl
text/x-diff
text/x-dsl
text/x-dtd
text/x-emacs-lisp
text/x-fortran
text/x-gtkrc
text/x-idl
text/x-install
text/x-ksysv-log
text/x-log
text/x-lyx
text/xmcd
text/xml-external-parsed-entity
text/xml
text/x-moc
text/x-pascal
text/x-readme
text/x-scheme
text/x-setext
text/x-sh
text/x-sql
text/x-texinfo
text/x-troff-man
text/x-troff-me
text/x-troff-mm
text/x-troff-ms
text/x-troff
video/mp4v-es
video/mpeg
video/parityfec
video/pointer
video/quicktime
video/vnd.fvt
video/vnd.motorola.video
video/vnd.motorola.videop
video/vnd.mpegurl
video/vnd.mts
video/vnd.nokia.interleaved-multimedia
video/vnd.vivo
video/vivo
video/x-anim
video/x-flc
video/x-flic
video/x-fli
video/x-mng
video/x-ms-asf
video/x-msvideo
video/x-sgi-movie
x-conference/x-cooltalk
